"""add filename fields

Revision ID: 4f1dea42f27e
Revises: fbc09b6944cc
Create Date: 2026-08-06 19:47:18.290875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1dea42f27e'
down_revision: Union[str, Sequence[str], None] = 'fbc09b6944cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'stored_filename')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
